# Generated by Django 2.2.5 on 2020-03-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170204_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Past_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('x_cord', models.IntegerField()),
                ('y_cord', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('detail', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idn', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('confirm_day', models.DateField()),
                ('case_no', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
        migrations.AddField(
            model_name='past_location',
            name='idn',
            field=models.ManyToManyField(to='first_app.Patient'),
        ),
    ]
