# Generated by Django 2.2.5 on 2020-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20200318_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='idn',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
