# Generated by Django 2.2.5 on 2020-03-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20200318_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='past_location',
            old_name='loc_name',
            new_name='location',
        ),
    ]
