# Generated by Django 2.2.5 on 2020-03-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20200319_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_location',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='past_location',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='past_location',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='past_location',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='past_location',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='past_location',
            name='x_cord',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='past_location',
            name='y_cord',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
