# Generated by Django 2.2.5 on 2020-03-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_remove_past_location_idn'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='locate',
            field=models.ManyToManyField(to='first_app.Past_Location'),
        ),
    ]
