# Generated by Django 2.2.5 on 2020-03-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_patient_locate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='locate',
            new_name='locations',
        ),
    ]
