# Generated by Django 2.2.5 on 2020-03-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20200319_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='locations',
        ),
        migrations.AddField(
            model_name='past_location',
            name='patient',
            field=models.ManyToManyField(to='first_app.Patient'),
        ),
    ]
